#!/usr/bin/env python3
"""Bake per-species animation-group metadata for pmd_sky_sprites.

The ROM's WAN group indices mean different things per species (slot 4
is Spearow's Hover but Pidgeot's FlapAround tumble), and the naming
lives in SpriteCollab's AnimData.xml, which mirrors the game's own
tables.  This writes data/anims.lua: for each dex, which group the
in-game ROM reader should render and how -- data only, no art.

Preference: Fly, then Hover, then FlapAround (a tumble whose first two
columns are a clean flap, masked by a frame subset), then Walk (in PMD
a flyer flies and a floater floats in its Walk cycle).

Usage: pmd_animdata.py [max_dex]   (default 251)
"""

import concurrent.futures
import pathlib
import re
import sys
import urllib.request

RAW = "https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/sprite"
ROOT = pathlib.Path(__file__).resolve().parent.parent / "pmd_sky_sprites"

PREFERENCE = ["Fly", "Hover", "FlapAround", "Walk"]
FRAME_SUBSETS = {"FlapAround": [1, 2]}


def fetch(url):
    try:
        with urllib.request.urlopen(url, timeout=30) as r:
            return r.read()
    except Exception:
        return None


def anims_of(xml):
    out = {}
    for m in re.finditer(rb"<Anim>(.*?)</Anim>", xml, re.S):
        a = m.group(1)
        name = re.search(rb"<Name>(.*?)</Name>", a)
        idx = re.search(rb"<Index>(\d+)</Index>", a)
        copy = re.search(rb"<CopyOf>(.*?)</CopyOf>", a)
        if name:
            out[name.group(1).decode()] = {
                "index": idx and int(idx.group(1)),
                "copy": copy and copy.group(1).decode(),
            }
    return out


def choose(dex):
    xml = fetch(f"{RAW}/{'%04d' % dex}/AnimData.xml")
    if not xml:
        return dex, None
    anims = anims_of(xml)
    for want in PREFERENCE:
        a = anims.get(want)
        seen = set()
        while a and a["index"] is None and a["copy"] and a["copy"] not in seen:
            seen.add(a["copy"])
            a = anims.get(a["copy"])
        if a and a["index"] is not None:
            return dex, {"anim": want, "group": a["index"],
                         "subset": FRAME_SUBSETS.get(want)}
    return dex, None


def main():
    max_dex = int(sys.argv[1]) if len(sys.argv) > 1 else 251
    rows = {}
    with concurrent.futures.ThreadPoolExecutor(max_workers=12) as pool:
        for dex, rec in pool.map(choose, range(1, max_dex + 1)):
            if rec:
                rows[dex] = rec
    lua = ["-- generated by scripts/pmd_animdata.py from PMDCollab",
           "-- SpriteCollab AnimData: which WAN animation group is each",
           "-- species' in-air (or airworthy Walk) cycle in the player's",
           "-- own ROM, and which frame columns to show.  Data only.",
           "return {"]
    for dex in sorted(rows):
        r = rows[dex]
        subset = ""
        if r["subset"]:
            subset = ", subset = { %s }" % ", ".join(
                str(i) for i in r["subset"])
        lua.append('  [%d] = { anim = "%s", group = %d%s },'
                   % (dex, r["anim"], r["group"], subset))
    lua.append("}")
    (ROOT / "data").mkdir(parents=True, exist_ok=True)
    (ROOT / "data" / "anims.lua").write_text("\n".join(lua) + "\n")
    counts = {}
    for r in rows.values():
        counts[r["anim"]] = counts.get(r["anim"], 0) + 1
    print("wrote %d species: %s" % (
        len(rows), ", ".join("%s=%d" % kv for kv in sorted(counts.items()))))


if __name__ == "__main__":
    main()
