-- generated by scripts/pmd_pack.py from PMDCollab/SpriteCollab
-- CC BY-NC 4.0 with attribution; see CREDITS.md
return {
  [150] = { file = "0150.png", anim = "Hover", fw = 48, fh = 72, frames = 13, durations = { 2, 2, 2, 6, 2, 2, 2, 2, 2, 2, 6, 2, 2 } },
  [176] = { file = "0176.png", anim = "Hover", fw = 24, fh = 48, frames = 15, durations = { 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2 } },
}
